### ISSUE TITLE
Could not find a requirements.txt

### ISSUE THREAD

**Issue by Pockyss** [leob03/mdmp#3]
hi, I noticed that the requirements.txt file is not available.​ Could you please provide it? It would greatly assist in setting up the environment properly.

Thank you for your help!

**Comment by leob03** [comment]
Hi @Pockyss, you should try to take a look at the https://github.com/leob03/mdmp?tab=readme-ov-file#1-setup-conda-environment section, it will guide you through environment set up! There is indeed no 'requirements.txt' file because we use an 'environment.yml' file.
